### ISSUE TITLE
3.0 still prevents dedicated server from starting. Same since 2.6. 2.5 was the last version to work.

### ISSUE THREAD

**Issue by dandin87** [shedaniel/IronJetpacks#13]
All of Fabric 3 2.6.9 - NA/EU official server testing

[10:56:44] [main/WARN]: Using deprecated ArtificeResourcePack#ofData! Issues may occur!
[10:56:44] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'iron-jetpacks'!
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
    at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]

Full Log
https://paste.lucko.me/2rgnbacdK3

**Comment by MaxNeedsSnacks** [comment]
https://github.com/shedaniel/IronJetpacks/blob/ffe20511383d7918f37b27e442feed11271ef664/src/main/java/com/blakebr0/ironjetpacks/item/JetpackItem.java#L48

This is an unsafe reference to JetpackModel and should be moved to a getter method:

```java
@Environment(EnvType.CLIENT)
private JetpackModel model;

@Environment(EnvType.CLIENT)
public JetpackModel getModel()
{
  if(model == null) model = new JetpackModel(this);
  return model;
}
```
